from checks.base import BaseChecker
from checks.repo_not_forked import RepoNotForkedChecker
from checks.commit_only_during_hackathon import CommitOnlyDuringHackathonChecker
from checks.only_valid_authors import OnlyValidAuthorsChecker
from checks.substantial_authors_contributions import SubstantialAuthorsContributionsChecker
# from checks.source_code_not_similar_to_other_user_project import SourceCodeSimilarityChecker
# from checks.no_commit_overlap_with_other_user_project import NoCommitOverlapWithOtherUserProjectChecker
